### ISSUE TITLE
Tools_v0.8.1 _12: Treemenu: Search is not working

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#590]
**SEVERITY:** Major

**MODULE:** Tools page (Bubble Chart)

**Platform:**
* Windows 7 / Chrome 45.0
* Windows 7 / Firefox 42.0
* MAC / Safari 8.0
* iPad Air 2 iOS(8.3) / Safari 8.0 
* Nexus 9 (5.0.1) / Chrome 45.0 
* Nexus 5 (5.1.1) / Chrome 44.0

**RELEASE:** v0.8.1

**STEPS TO REPRODUCE:**
1)	Navigate to URL: http://128.199.60.177:8080/tools/
2)	Tools page is loaded.
3)	Click Y axis or X axis label
4)	Write some text in search. For example “Population”
5)	Note that search is not working whether the given option is present or not.

**ACTUAL RESULTS:**
Search is not working whether the given option is present or not.

**EXPECTED RESULTS:** 
Search should work properly

**SCREENSHOT:**

![tools_page_v0 8 1 _04](https://cloud.githubusercontent.com/assets/9950837/10247305/9ee66d18-6931-11e5-8b42-f491e84b01f6.png)

**Comment by angieskazka** [comment]
Where to hack:
treemenu.js 

How to hack:
see how the search is designed in the tree menu
understand that the search may run across multiple languages!
fix the bug (this issue). probably the indicator data is incorrectly attached, so that the search has troubles traversing the tree
suggest optimisation and refactoring of search if you find it relevant

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/673

**Comment by angieskazka** [comment]
yes, search is now working, but it's searching by indicator ID's (gdp, pop, gini, u5mr etc...)
by a plain coincidence names and ids often fall close, so you are able to find the items, but consider this one:

![image](https://cloud.githubusercontent.com/assets/3648190/10508375/01ac7f24-7327-11e5-86a0-ba290d0520d2.png)

![image](https://cloud.githubusercontent.com/assets/3648190/10508393/286ce1e4-7327-11e5-87bd-55a4871456ce.png)

search should use reverse translation, not IDs of the indicators
translations should work across many languages: if you switch the preview page to Swedish, it should be able to search both by "GDP" and "BNP"

![image](https://cloud.githubusercontent.com/assets/3648190/10508469/8fec567e-7327-11e5-8aa5-102aeb552c4b.png)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/676
Done, It will search across all languages, but results will show in current language. Is it correct?

**Comment by angieskazka** [comment]
Yes, correct. It should search across all languages it accumulated while i was switching the language, but results will show in current language 

Some bugs are still there, please give it a good test!
`we` returns Wealth (correct)
`hea` returns nothing (should be Health)
`dist`, `and`, `ineq` return Income distribution and inequality (correct)
`inco` returns nothing (should return the same)
`mort` and rat return Child mortality rate (correct)
`chi` returns nothing (should return the same)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/686

**Comment by angieskazka** [comment]
the above closed the issue

**Comment by angieskazka** [comment]
this came back. @sergey-filipenko please help!

**Comment by angieskazka** [comment]
fixed now through #508
