### ISSUE TITLE
v0.8.3_02: By clicking “Expand”, the chart is not expanded properly

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi#689]
**SUMMARY:** 
**1)**  By clicking “Expand”, the chart is not expanded properly
**2)**  By clicking “Expand”, “Expand” icon is not changed to “Restore” icon

**SEVERITY:** Major

**MODULE:** 
* Bubble Chart
* Mountain Chart

**Platform:**
* Windows 7 / Chrome 45.0
* Windows 7 / Firefox 42.0

**RELEASE:** v0.8.3

**STEPS TO REPRODUCE:**
1)	Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.3/preview/bubblechart.html
2)	Bubble chart page will be loaded
3)	Click “Full” button under RESPONSIVENESS
4)	Click “Expand”
5)	Note that the chart is not expanded properly
6)	Also note that “Expanded” icon is not changed to “Restore” icon

 **ACTUAL RESULTS:**
By clicking “Expand”, the chart is not expanded properly and also that “Expanded” icon is not changed to “Restore” icon

**EXPECTED RESULTS:** 
By clicking “Expand”, the chart should be expanded properly and “Expanded” icon should be changed to “Restore” icon

**SCREENSHOT:**

![v0 8 3_02](https://cloud.githubusercontent.com/assets/9950837/10540774/8a280fa0-7424-11e5-92aa-ff90cfbc2a78.png)

**Comment by dab2000** [comment]
couldn't reproduce on http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html (Win 10, Chrome 46), 
but is reproduced on http://static.gapminderdev.org/vizabi/release/v0.8.3/preview/bubblechart.html.

**Comment by arthurcamara1** [comment]
Fixed.

**Comment by k6Labz** [comment]
**Retest Result:** Failed

**Testing Environment:** http://static.gapminderdev.org/vizabi/release/v0.8.3/preview/mountainchart.html 

**Screenshot:** 

![11](https://cloud.githubusercontent.com/assets/9950837/10599298/1d5c35a6-771a-11e5-9668-143c908c94bb.png)

**Comment by angieskazka** [comment]
@k6Labz 
yes, it's still broken in 0.8.3, we know it. it will always be broken there
this issue was closed in 0.8.4 which means that it was fixed in 0.8.4 

please stop testing 0.8.3
